//styles
import styles from "../styles/Welcome.module.css";

//next
import Link from "next/link";
import Head from "next/head";

export default function Home() {
  return (
    <main className={styles.Welcome}>
      <Head>
        <title>Pokedex | App</title>
        <meta name="description" content="Generated by create-next-app" />
        <link
          rel="shortcut icon"
          href="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png"
          type="image/x-icon"
        />
      </Head>

      <button>
        <Link href={"/pokedex"}>Go to Pokedex</Link>
      </button>

      <footer>
        Website created by{" "}
        <a href="https://www.instagram.com/iamryaan011/" target="blank">
          @iamryaan011
        </a>{" "}
        with{" "}
        <a href="https://pokeapi.co/" target="blank">
          PokeAPI
        </a>
      </footer>
    </main>
  );
}
